version: '3.8'

services:
  shottower:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: unless-stopped
    networks:
      - dokploy-network
    resources:
      limits:
        cpus: 2
        memory: 4g
#     volumes:
#       - tmp_data:/tmp


# volumes:
#   tmp_data:

networks:
  dokploy-network:
    external: true